name: app
description: "Данное приложение разработано для предоставления пользователю сборника белорусских рецептов, раскрывающих богатство национальных традиций."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_svg: ^1.0.3
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
    android: true
    ios: true
    image_path: "lib/assets/icons/icon.png"
    min_sdk_android: 29

flutter:
  uses-material-design: true

  assets:
  - lib/assets/data/
  - lib/assets/images/
  - lib/assets/icons/
  - lib/assets/